layout_spectrum: 0.2831541
color:
  saturation: 0.2150538
  brandStrength: 0.6324509
  lightness: 0.5501792
  rhythmicContrast: 0.546595
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.1666667
name: Our First Flat
